CRM.Web/Controllers/CallController.cs
using CRM.Web.Data.Contrat;
using CRM.Web.Models;
using CRM.Web.Resources;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace CRM.Web.Controllers
{
    [Authorize("Employee")]
    public class CallController : Controller
    {
        private readonly IGenericRepository<Call> _callRepository;
        private readonly IGenericRepository<Customer> _customerRepository;
        private readonly ILogManager _logManager;
        private readonly IStringLocalizer<SharedLangResources> _localization;

        public CallController(IGenericRepository<Call> callRepository, IGenericRepository<Customer> customerRepository, 
            ILogManager logManager, IStringLocalizer<SharedLangResources> localization)
        {
            _callRepository = callRepository;
            _customerRepository = customerRepository;
            _logManager = logManager;
            _localization = localization;
        }


        [HttpGet]
        public async Task<ActionResult> Index(int? customerNo, int page = 1, int pageSize = 10)
        {
            if (customerNo is null)
            {
                var response = await _callRepository.GetPaged(page, pageSize);
                if (response.Resultats is null)
                {
                    return NotFound();
                }
                var total = await _callRepository.CountAll();
                var totalPages = (int)Math.Ceiling((double)total.Resultat / pageSize);

                var callList = new List<CallViewsModel>();

                foreach (var item in response.Resultats)
                {
                    callList.Add(new CallViewsModel
                    {
                        CallNo = item.CallNo,
                        CustomerNo = item.CustomerNo,
                        customer = (await _customerRepository.GetById(item.CustomerNo)).Resultat,
                        Description = item.Description,
                        DateTimeofCall = item.DateTimeofCall,
                        Subject = item.Subject
                    });
                }

                var model = new PagedList<CallViewsModel>
                {
                    ListElements = callList,
                    pageSize = totalPages,
                    pageIndex = page,
                };

                return View(model);
            }
            else
            {
                var response = await _callRepository.GetAll();
                if (response.Resultats is null)
                {
                    return NotFound();
                }

                var list = response.Resultats.Where(c=> c.CustomerNo == customerNo);

                var total = list.Count();
                var totalPages = (int)Math.Ceiling((double)total / pageSize);

                var callList = new List<CallViewsModel>();

                foreach (var item in list)
                {
                    callList.Add(new CallViewsModel
                    {
                        CallNo = item.CallNo,
                        CustomerNo = item.CustomerNo,
                        customer = (await _customerRepository.GetById(item.CustomerNo)).Resultat,
                        Description = item.Description,
                        DateTimeofCall = item.DateTimeofCall,
                        Subject = item.Subject
                    });
                }

                var model = new PagedList<CallViewsModel>
                {
                    ListElements = callList,
                    pageSize = totalPages,
                    pageIndex = page,
                };

                return View(model);

            }
        }

        // GET: CallController



        // GET: CallController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var call = await _callRepository.GetById(id);
            if (call.Resultat == null)
                return NotFound();

            var customer = await _customerRepository.GetById(call.Resultat.CustomerNo);
            if (customer.Resultat == null)
                return NotFound();

            var callview = new CallViewsModel(call.Resultat, customer.Resultat);
            
            return View(callview);
        }

        // GET: CallController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CallController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Call call)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = await _callRepository.Add(call);
                    if (result.IsCorrect)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.ErrorMessage = _localization["Echec"];
                        return View(call);
                    }
                }

                ViewBag.ErrorMessage = _localization["Employee.allfields"];
                return View(call);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = _localization["Echec"];

                _logManager.AddLog("Error", ex.Message, ex.ToString());
                return View(call);
            }
        }

        // GET: CallController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var call = await _callRepository.GetById(id);
            if (call.Resultat == null)
                return NotFound();

            return View(call.Resultat);
        }

        // POST: CallController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Call call)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = await _callRepository.Update(call);
                    if (result.IsCorrect)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.ErrorMessage = _localization["Echec"];
                        return View(call);
                    }
                }

                ViewBag.ErrorMessage = _localization["Employee.allfields"];
                return View(call);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = _localization["Echec"];

                _logManager.AddLog("Error", ex.Message, ex.ToString());
                return View(call);
            }
        }

        // GET: CallController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var call = await _callRepository.GetById(id);
            if (call.Resultat == null)
                return NotFound();

            var customer = await _customerRepository.GetById(call.Resultat.CustomerNo);
            if (customer.Resultat == null)
                return NotFound();

            var callview = new CallViewsModel(call.Resultat, customer.Resultat);

            return View(callview);
        }

        // POST: CallController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Deleted(int id)
        {
            var resu = await _callRepository.Remove(id);
            if (resu.IsCorrect)
            {
                return RedirectToAction(nameof(Index));
            }
            ViewBag.ErrorMessage = _localization["Echec"];
            return NoContent();
        }
    }
}

CRM.Web/Controllers/CustomerController.cs
using CRM.Web.Data.Contrat;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CRM.Web.Models;
using Microsoft.Extensions.Localization;
using CRM.Web.Resources;

namespace CRM.Web.Controllers
{
    [Authorize("Manager")]
    public class CustomerController : Controller
    {
        private readonly IGenericRepository<Customer> _customerRepository;
        private readonly ILogManager _logManager;
        private readonly IStringLocalizer<SharedLangResources> _localization;

        public CustomerController(IGenericRepository<Customer> customerRepository,ILogManager logManager, IStringLocalizer<SharedLangResources> localization)
        {
            _customerRepository = customerRepository;
            _logManager = logManager;
            _localization = localization;
        }
        // GET: CustomerController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Index(int page = 1, int pageSize = 10)
        {
            var response = await _customerRepository.GetPaged(page, pageSize);
            if (response.Resultats is null)
            {
                return NotFound();
            }
            var total = await _customerRepository.CountAll();
            var totalPages = (int)Math.Ceiling((double)total.Resultat / pageSize);

            var model = new PagedList<Customer>
            {
                ListElements = response.Resultats,
                pageSize = totalPages,
                pageIndex = page,
            };

            return View(model);
        }


        // GET: CustomerController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var customer = await _customerRepository.GetById(id);
            if (customer.Resultat == null)
                return NotFound();

            return View(customer.Resultat);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CustomerViewsModel customerViewsModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = await _customerRepository.Add(new Customer(customerViewsModel));
                    if (result.IsCorrect)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.ErrorMessage = _localization["Echec"];
                        return View(customerViewsModel);
                    }
                }

                ViewBag.ErrorMessage = _localization["Employee.allfields"];
                return View(customerViewsModel);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = _localization["Echec"];

                _logManager.AddLog("Error", ex.Message, ex.ToString());
                return View(customerViewsModel);
            }
        }

        // GET: CustomerController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var customer = (await _customerRepository.GetById(id));
            if (customer.Resultat == null)
                return NotFound();
            var model = new CustomerViewsModel(customer.Resultat);
            return View(model);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CustomerViewsModel customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = await _customerRepository.Update(new Customer(customer));
                    if (result.IsCorrect)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.ErrorMessage = _localization["Echec"];
                        return View(customer);
                    }
                }

                ViewBag.ErrorMessage = _localization["Employee.allfields"];
                return View(customer);
            }
            catch(Exception ex)
            {
                ViewBag.ErrorMessage = _localization["Echec"];

                _logManager.AddLog("Error", ex.Message, ex.ToString());
                return View(customer);
            }
        }

        // GET: CustomerController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var customer = (await _customerRepository.GetById(id));
            if (customer.Resultat == null)
                return NotFound();

            return View(customer.Resultat);
        }

        // POST: CustomerController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Deleted(int id)
        {
            var resu = await _customerRepository.Remove(id);
            if (resu.IsCorrect)
            {
                return RedirectToAction(nameof(Index));
            }
            ViewBag.ErrorMessage = _localization["Echec"];
            return NoContent();
        }
    }
}

CRM.Web/Views/Shared/_Layout.cshtml
@inject IAuthorizationService AuthorizationService


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRM.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRM.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">CRM App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Home">@SharedLocalizer["Home"]</a>
                        </li>
                        @if ((await AuthorizationService.AuthorizeAsync(User, "Employee")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Call">@SharedLocalizer["Calls"]</a>
                            </li>
                        }
                        @if ((await AuthorizationService.AuthorizeAsync(User, "Manager")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Customer">@SharedLocalizer["Customers"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Report">@SharedLocalizer["Reports"]</a>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <partial name="_SelectLanguage" />
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Employee" asp-action="Logout">@SharedLocalizer["Logout"]</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 mt-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRM.Web Ngueukeu Tiofack Lionnel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CRM.Web/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" 
          method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> <select name="culture" onchange="this.form.submit();"
          asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>